version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_tech_fase_5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  config-server:
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: config-server:v1
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    networks:
      - app-network

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: eureka-server:v1
    ports:
      - "8761:8761"
    depends_on:
      - postgres
      - config-server
    networks:
      - app-network

volumes:
  postgres-data:

networks: 
  app-network:
    driver: bridge
