version: '3'

services:
  config-server:
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: config-server:v1
    ports:
      - "8888:8888"
    networks:
      - app-network

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: eureka-server:v1
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - app-network

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway:v1
    ports:
      - "8765:8765"
    depends_on:
      - config-server
      - eureka-server
    networks:
      - app-network

  auth:
    container_name: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    image: auth:v1
    depends_on:
      - config-server
      - eureka-server
    networks:
      - app-network

  usuario:
    container_name: usuario
    build:
      context: ./usuario
      dockerfile: Dockerfile
    image: usuario:v1
    depends_on:
      - config-server
      - eureka-server
    networks:
      - app-network
    volumes:
      - ./db/main/tech-fase-5/usuario:/app/db

  item:
    container_name: item
    build:
      context: ./item
      dockerfile: Dockerfile
    image: item:v1
    depends_on:
      - config-server
      - eureka-server
    networks:
      - app-network
    volumes:
      - ./db/main/tech-fase-5/item:/app/db

  carrinho:
    container_name: carrinho
    build:
      context: ./carrinho
      dockerfile: Dockerfile
    image: carrinho:v1
    depends_on:
      - config-server
      - eureka-server
    networks:
      - app-network
    volumes:
      - ./db/main/tech-fase-5/carrinho:/app/db

  pedido:
    container_name: pedido
    build:
      context: ./pedido
      dockerfile: Dockerfile
    image: pedido:v1
    depends_on:
      - config-server
      - eureka-server
    networks:
      - app-network
    volumes:
      - ./db/main/tech-fase-5/pedido:/app/db

networks: 
  app-network:
    driver: bridge
